---
- hosts: dev
  becomes: true
  tasks:
    - name: install python pip
	  yum:
	    name: python-pip
		state: present
	- name: install docker-py python module
	  pip:
	    name: docker-py
		state: present
	-name: start the container
	 docker_container:
	     name: tech-v
		 image: "umesh4321/tech-v"
		 state: started
		 published_ports:
		   - 0.0.0.0:8080:8080
  
