---
- hosts: dev
  become: true
  tasks:
   - name: start docker
     service:
       name: docker
       state: started
       enabled: yes
   - name: start the container
     docker_container:
       name: projectfinal
       image: "umesh4321/projectfinal:{{DOCKER_TAG}}"
       state: started
       published_ports:
       - 0.0.0.0:8080:8888
       command: sleep infinity
       tty: true
       detach: true
