---
- hosts: all
  become: true
  tasks:
   - name: create docker image using jar file
     command: docker build . -t simple-devops-image:latest
     args:
       chdir: /opt/docker
   - name: create tag to image
     command: docker tag simple-devops-image umesh4321/simple-devops-image
   - name: push image on to docker hub
     command: docker push umesh4321/simple-devops-image
   - name: remove image from ansible server
     command: docker rmi tomcat simple-devops-image:latest umesh4321/simple-devops-image
     ignore_errors: yes
