---
- hosts: all
  become: yes
  tasks:
   - name: stop running container
     command: docker stop simple-devops-container
     ignore_errors: yes
   - name: remove stop docker container
     command: docker rm simple-devops-container
     ignore_errors: yes
   - name: remove current docker image
     command: docker rmi umesh4321/simple-devops-image:latest
     ignore_errors: yes
   - name: pull docker image from dockerhub
     command: docker pull umesh4321/simple-devops-image:latest
   - name: create docker container
     command: docker run -d --name simple-devops-container -p 8080:8080 umesh4321/simple-devops-image:latest
